# This is a basic workflow to help you get started with Actions
name: Node.js CI # name of the workflow

on:     # triggers the workflow on push to the main branch
  push:
    branches: [ "main" ]

jobs:       # all the jobs that will run as part of this workflow
  build:    # first job, named "build"
    runs-on: ubuntu-latest   # the type of runner that the job will run on/server that will execute the job

    defaults: # default settings for all the steps in this job
      run:
        working-directory: Demo   # set the default working directory for all the run steps to "Demo"

    strategy: 
      matrix:  # defines a matrix of different configurations to run the job with, in this case, different versions of Node.js
        node-version: [20.x, 22.x]

    steps:          # the individual steps that will be executed as part of this job
    - uses: actions/checkout@v4  # checks out the repository code so that the workflow can access it and run commands on it, such as installing dependencies and running tests

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4       # sets up the specified version of Node.js for the job, allowing you to run your Node.js application and tests in that environment
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: Demo/package-lock.json  # specify the path to the package-lock.json file for caching npm dependencies

    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
